version: '3.8'

services:
  spring_app:
    image: denysmatvieiev/code-launch-backend
    container_name: spring_app
    ports:
      - '3004:3004'
    volumes:
      - ./src/main/java:/app/src/main/java
      - ./src/main/resources:/app/src/main/resources
      - ./pom.xml:/app/pom.xml
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://turntable.proxy.rlwy.net:15640/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: dkKarLfDxDEQyoxFQrXXhbfnHmAfsUDm
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_DATABASE: postgresql
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_SERVER_PORT: 3004
    networks:
      - app-network

volumes:
  postgres_data:
    external: true

networks:
  app-network:
    driver: bridge
